"""Epic Decomposer Agent v3.0 - Using OpenAI Agents SDK

Enterprise-grade epic decomposition using the official OpenAI Agents SDK.

Architecture:
- Uses Agent, Runner from openai-agents SDK
- OpenAIChatCompletionsModel for Gemini
- Structured outputs with Pydantic models
- Input guardrails for validation
- Proper error handling and logging

Design Principles:
1. Use proper SDK primitives (Agent, Runner, output_type)
2. Gemini as the sole model provider
3. Structured outputs for type-safe responses
4. Input validation via guardrails
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, AsyncGenerator

from dotenv import load_dotenv, find_dotenv
from openai import AsyncOpenAI
from pydantic import BaseModel, Field

# OpenAI Agents SDK imports
from agents import (
    Agent,
    Runner,
    ModelSettings,
    GuardrailFunctionOutput,
    RunContextWrapper,
    TResponseInputItem,
    input_guardrail,
    set_tracing_disabled,
)
from agents.models.openai_chatcompletions import OpenAIChatCompletionsModel

# Load environment
load_dotenv(find_dotenv())

logger = logging.getLogger("epic_decomposer")

# Disable tracing since we're not using OpenAI API keys for traces
set_tracing_disabled(True)

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Model name
GEMINI_MODEL = os.getenv("GEMINI_MODEL_NAME", "models/gemini-3-flash-preview")

# Output hardening: nudge the model to emit only JSON (no markdown, no prose)
STRICT_JSON_ONLY = """

STRICT OUTPUT RULES:
- Output MUST be valid JSON only (no markdown/code fences).
- Do NOT include any extra commentary outside JSON.
"""

# For external reference (used by agents.py)
MODEL_NAME = GEMINI_MODEL

# Token limits
MAX_EPIC_CHARS = 2000
MAX_STORIES = 12
MIN_STORIES = 3

# Timeout settings
HTTP_TIMEOUT = float(os.getenv("AGENT_HTTP_TIMEOUT", "60"))

# ═══════════════════════════════════════════════════════════════════════════════
# OPENAI CLIENT (Gemini via OpenAI-compatible API)
# ═══════════════════════════════════════════════════════════════════════════════

gemini_client: Optional[AsyncOpenAI] = None
if GEMINI_API_KEY:
    gemini_client = AsyncOpenAI(
        api_key=GEMINI_API_KEY,
        base_url=os.getenv(
            "GEMINI_BASE_URL",
            "https://generativelanguage.googleapis.com/v1beta/openai/",
        ),
        timeout=HTTP_TIMEOUT,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# PYDANTIC OUTPUT MODELS (Structured Outputs)
# ═══════════════════════════════════════════════════════════════════════════════

class StoryOutput(BaseModel):
    """A single user story generated by the agent."""
    title: str = Field(description="Clear, action-oriented story title (5-12 words)")
    persona: str = Field(default="User", description="Target user persona")
    user_value: str = Field(description="Business value this story delivers")
    acceptance_criteria: List[str] = Field(
        description="3-6 testable acceptance criteria in Given/When/Then format"
    )
    risks: List[str] = Field(default_factory=list, description="Potential implementation risks")


class StoriesOutput(BaseModel):
    """The complete output from the story generation agent."""
    stories: List[StoryOutput] = Field(description="List of generated user stories")


class EpicAnalysis(BaseModel):
    """Analysis of the epic for context."""
    summary: str = Field(description="Brief summary of what the epic is about")
    primary_users: List[str] = Field(description="Target users for this epic")
    key_capabilities: List[str] = Field(description="Main capabilities needed")
    constraints: List[str] = Field(default_factory=list, description="Known constraints")


class InputValidation(BaseModel):
    """Result of input validation."""
    is_valid: bool = Field(description="Whether the input is valid for decomposition")
    reason: str = Field(description="Reason for validation result")


# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def truncate_text(text: Optional[str], max_chars: int = MAX_EPIC_CHARS) -> str:
    """Truncate text to maximum characters."""
    if not text:
        return ""
    text = text.strip()
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "..."


def create_gemini_model() -> OpenAIChatCompletionsModel:
    """Create model using Gemini client."""
    if not gemini_client:
        raise RuntimeError("GEMINI_API_KEY is not configured")
    return OpenAIChatCompletionsModel(
        model=GEMINI_MODEL,
        openai_client=gemini_client,
    )


def get_model():
    """Get the Gemini model."""
    model = create_gemini_model()
    return model, "gemini"


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT GUARDRAIL
# ═══════════════════════════════════════════════════════════════════════════════

@input_guardrail
async def validate_epic_input(
    ctx: RunContextWrapper[None],
    agent: Agent,
    input: str | list[TResponseInputItem],
) -> GuardrailFunctionOutput:
    """Validate that the input is a valid epic description."""
    # Extract text from input
    if isinstance(input, list):
        parts: List[str] = []
        for item in input:
            if isinstance(item, dict):
                content = item.get("content", "")
                if isinstance(content, str):
                    parts.append(content)
            elif isinstance(item, str):
                parts.append(item)
        text = " ".join(parts)
    else:
        text = str(input)
    
    text = text.strip()
    
    # Basic validation
    if not text:
        return GuardrailFunctionOutput(
            output_info={"reason": "Empty input"},
            tripwire_triggered=True,
        )
    
    if len(text) < 20:
        return GuardrailFunctionOutput(
            output_info={"reason": "Input too short - need at least 20 characters"},
            tripwire_triggered=True,
        )
    
    # Check for obvious non-epic content
    lower_text = text.lower()
    if any(word in lower_text for word in ["hello", "hi there", "what's up", "how are you"]):
        if len(text) < 50:  # Only trip if it's just a greeting
            return GuardrailFunctionOutput(
                output_info={"reason": "Input appears to be a greeting, not an epic"},
                tripwire_triggered=True,
            )
    
    return GuardrailFunctionOutput(
        output_info={"reason": "Valid epic input"},
        tripwire_triggered=False,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# AGENT DEFINITIONS
# ═══════════════════════════════════════════════════════════════════════════════

def create_story_generator_agent(model, target_stories: int) -> Agent:
    """Create the story generator agent with structured output."""
    
    instructions = f"""You are an expert Agile Product Owner specializing in epic decomposition.

Your task is to decompose an epic description into EXACTLY {target_stories} user stories.

CRITICAL REQUIREMENTS:
1. Generate EXACTLY {target_stories} user stories - no more, no less
2. Each story must be independent and deliverable in a single sprint
3. Stories should follow the INVEST criteria (Independent, Negotiable, Valuable, Estimable, Small, Testable)
4. Each story needs 3-6 acceptance criteria in Given/When/Then format

OUTPUT FORMAT:
- title: Clear, action-oriented (5-12 words, e.g., "Implement user login with email verification")
- persona: Target user (e.g., "Registered User", "Admin", "Guest")
- user_value: Why this matters to the user/business
- acceptance_criteria: List of 3-6 testable criteria in Given/When/Then format
- risks: 0-2 potential implementation risks

IMPORTANT: You MUST generate exactly {target_stories} stories. Count them before responding.""" + STRICT_JSON_ONLY

    return Agent(
        name="Story Generator",
        instructions=instructions,
        model=model,
        output_type=StoriesOutput,
        model_settings=ModelSettings(
            temperature=0.3,
            max_tokens=4000,
        ),
        input_guardrails=[validate_epic_input],
    )


# ═══════════════════════════════════════════════════════════════════════════════
# DATABASE HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

# Supabase client (optional - for fetching existing children)
try:
    from app.core.dependencies import supabase
except ImportError:
    supabase = None


def _fetch_existing_children(epic_id: str) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Fetch existing child issues for an epic (best effort)."""
    if not supabase:
        return [], []
    try:
        children_res = supabase.table("issues").select(
            "id,title,type,acceptance_criteria"
        ).eq("epic_id", epic_id).execute()
        children = getattr(children_res, 'data', []) or []
    except Exception as e:
        logger.debug(f"Failed to fetch children for epic {epic_id}: {e}")
        children = []
    return children, []


def _summarize_children(children: List[Dict[str, Any]]) -> str:
    """Summarize existing children for context."""
    if not children:
        return "(none)"
    out = []
    for c in children[:5]:
        title = (c.get('title') or '')[:80]
        out.append(f"- {title}")
    if len(children) > 5:
        out.append(f"... and {len(children) - 5} more")
    return "\n".join(out)


# ═══════════════════════════════════════════════════════════════════════════════
# POST-PROCESSING
# ═══════════════════════════════════════════════════════════════════════════════

def normalize_story(story: StoryOutput, index: int) -> Dict[str, Any]:
    """Convert StoryOutput to dictionary with defaults."""
    return {
        "title": story.title or f"Story {index + 1}",
        "persona": story.persona or "User",
        "user_value": story.user_value or "Delivers value to users",
        "acceptance_criteria": story.acceptance_criteria or ["Acceptance criteria to be defined"],
        "risks": story.risks or [],
    }


def compute_quality_score(
    stories: List[Dict[str, Any]],
    warnings: List[str],
    target_count: int,
) -> float:
    """Calculate quality score for generated stories."""
    if not stories:
        return 0.0
    
    score = 0.0
    
    # Story count match (30%)
    count_ratio = len(stories) / target_count if target_count > 0 else 1.0
    score += 0.3 * min(count_ratio, 1.0)
    
    # Acceptance criteria quality (40%)
    ac_scores = []
    for s in stories:
        ac = s.get("acceptance_criteria", [])
        if len(ac) >= 3:
            ac_scores.append(1.0)
        elif len(ac) >= 1:
            ac_scores.append(0.5)
        else:
            ac_scores.append(0.0)
    if ac_scores:
        score += 0.4 * (sum(ac_scores) / len(ac_scores))
    
    # Completeness (20%)
    complete_count = sum(
        1 for s in stories
        if len(s.get("user_value", "")) > 10 and len(s.get("persona", "")) > 0
    )
    score += 0.2 * (complete_count / len(stories))
    
    # Warning penalty (10%)
    warning_penalty = min(len(warnings) * 0.02, 0.1)
    score += 0.1 - warning_penalty
    
    return round(min(score, 1.0), 3)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN PIPELINE
# ═══════════════════════════════════════════════════════════════════════════════

async def run_with_fallback(
    epic_description: str,
    target_stories: int,
) -> Tuple[Optional[StoriesOutput], List[str], str]:
    """Run the agent with Gemini."""
    warnings: List[str] = []
    
    if not gemini_client:
        raise RuntimeError("GEMINI_API_KEY is not configured")
    
    try:
        logger.info("Attempting generation with Gemini...")
        model = create_gemini_model()
        agent = create_story_generator_agent(model, target_stories)
        result = await Runner.run(agent, epic_description)
        if result.final_output and isinstance(result.final_output, StoriesOutput):
            logger.info(f"Gemini succeeded: {len(result.final_output.stories)} stories")
            return result.final_output, warnings, "gemini"
    except Exception as e:
        logger.error(f"Gemini generation failed: {e}")
        warnings.append(f"Gemini generation failed: {str(e)[:100]}")
    
    return None, warnings, "none"


async def decompose_epic_stream(
    epic_description: str,
    max_stories: int = 6,
    epic_id: Optional[str] = None,
    user_prompt: Optional[str] = None,
) -> AsyncGenerator[Dict[str, Any], None]:
    """Stream the epic decomposition pipeline.
    
    Yields progress events and final result.
    """
    # Validate inputs
    if not GEMINI_API_KEY:
        yield {"type": "error", "error": "GEMINI_API_KEY is not configured"}
        return
    
    if not epic_description or not epic_description.strip():
        yield {"type": "error", "error": "Epic description is required"}
        return
    
    # Bound story count
    target_stories = max(MIN_STORIES, min(max_stories, MAX_STORIES))
    
    # Prepare input
    epic_text = truncate_text(epic_description.strip(), MAX_EPIC_CHARS)
    
    # Add user prompt context if provided
    if user_prompt:
        epic_text = f"{epic_text}\n\nAdditional context: {truncate_text(user_prompt, 500)}"
    
    yield {"type": "progress", "stage": "init", "message": "Starting decomposition...", "percent": 5}
    
    # Fetch existing children for context
    existing_children = []
    if epic_id:
        existing_children, _ = _fetch_existing_children(epic_id)
        if existing_children:
            children_summary = _summarize_children(existing_children)
            epic_text = f"{epic_text}\n\nExisting stories (avoid duplicates):\n{children_summary}"
    
    yield {"type": "progress", "stage": "generating", "message": f"Generating {target_stories} stories...", "percent": 20}
    
    # Run the agent with fallback
    try:
        output, warnings, provider = await run_with_fallback(epic_text, target_stories)
    except Exception as e:
        logger.error(f"Agent execution failed: {e}")
        yield {"type": "error", "error": f"Agent execution failed: {str(e)}"}
        return
    
    yield {"type": "progress", "stage": "processing", "message": "Processing results...", "percent": 80}
    
    # Process results
    if not output or not output.stories:
        yield {
            "type": "result",
            "data": {
                "success": False,
                "data": None,
                "error": "No stories generated",
                "warnings": warnings,
                "quality_score": 0.0,
            }
        }
        return
    
    # Normalize stories
    final_stories = [
        normalize_story(story, idx)
        for idx, story in enumerate(output.stories)
    ]
    
    # Compute quality score
    quality_score = compute_quality_score(final_stories, warnings, target_stories)
    
    # Check story count
    if len(final_stories) != target_stories:
        warnings.append(f"Requested {target_stories} stories, got {len(final_stories)}")
    
    logger.info(
        "Pipeline complete: %d stories, quality=%.2f, provider=%s",
        len(final_stories), quality_score, provider
    )
    
    # Build final result
    result = {
        "success": len(final_stories) > 0,
        "data": {"stories": final_stories} if final_stories else None,
        "raw_output": output.model_dump_json() if output else None,
        "error": None if final_stories else "No stories generated",
        "warnings": warnings,
        "duplicate_matches": [],
        "quality_score": quality_score,
        "warnings_count": len(warnings),
        "analyst_insights": None,
        "review_feedback": None,
        "provider": provider,
    }
    
    yield {"type": "result", "data": result}
    yield {"type": "progress", "stage": "complete", "message": "Done", "percent": 100}


async def decompose_epic(
    epic_description: str,
    max_stories: int = 6,
    epic_id: Optional[str] = None,
    user_prompt: Optional[str] = None,
) -> Dict[str, Any]:
    """Synchronous wrapper for decompose_epic_stream."""
    final_result = {
        "success": False,
        "data": None,
        "raw_output": None,
        "error": "Unknown error",
    }
    
    async for event in decompose_epic_stream(epic_description, max_stories, epic_id, user_prompt):
        if event["type"] == "result":
            final_result = event["data"]
        elif event["type"] == "error":
            final_result = {
                "success": False,
                "data": None,
                "raw_output": None,
                "error": event["error"],
            }
    
    return final_result


async def regenerate_story(
    epic_description: str,
    epic_id: Optional[str],
    original_story: Dict[str, Any],
    feedback: str,
) -> Dict[str, Any]:
    """Regenerate a single story based on user feedback."""
    title = original_story.get("title", "Story")
    ac_list = original_story.get("acceptance_criteria", [])
    
    guidance = f"""REGENERATION REQUEST:
Original story: {title}
Current acceptance criteria: {', '.join(ac_list[:5])}

User feedback: {feedback}

Generate an improved version of this story addressing the feedback.
Generate exactly 1 story."""
    
    return await decompose_epic(
        epic_description=epic_description,
        max_stories=1,
        epic_id=epic_id,
        user_prompt=guidance,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# UTILITY EXPORTS (for tests)
# ═══════════════════════════════════════════════════════════════════════════════

def repair_json(raw: str) -> Optional[Dict[str, Any]]:
    """Attempt to parse/repair JSON from raw text (for backwards compatibility)."""
    if not raw:
        return None
    
    # Try direct parse
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    
    # Try to extract JSON from markdown fence
    import re
    fence_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', raw)
    if fence_match:
        try:
            return json.loads(fence_match.group(1).strip())
        except json.JSONDecodeError:
            pass
    
    # Try to find JSON object
    brace_start = raw.find('{')
    if brace_start >= 0:
        try:
            return json.loads(raw[brace_start:])
        except json.JSONDecodeError:
            pass
    
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# JIRA INTEGRATION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

async def decompose_epic_from_jira(
    epic_key: str,
    integration_id: str,
    workspace_id: str,
    max_stories: int = 6,
    user_prompt: Optional[str] = None,
    push_to_jira: bool = False
) -> Dict[str, Any]:
    """
    Decompose an epic fetched directly from Jira and optionally push stories back.
    
    Args:
        epic_key: Jira epic key (e.g., 'PROJ-123')
        integration_id: Integration credentials ID
        workspace_id: Workspace ID
        max_stories: Maximum number of stories to generate
        user_prompt: Optional user guidance
        push_to_jira: Whether to push generated stories back to Jira
        
    Returns:
        Decomposition result with Jira keys if pushed
    """
    from app.services.jira import JiraOAuthManager, JiraAPIClient, JiraSyncService
    from app.core.config import settings
    
    # Get authenticated Jira client
    if not settings.JIRA_OAUTH_CLIENT_ID or not settings.JIRA_OAUTH_CLIENT_SECRET:
        return {
            "success": False,
            "error": "Jira OAuth not configured. Please set JIRA_OAUTH_CLIENT_ID and JIRA_OAUTH_CLIENT_SECRET."
        }
    
    oauth_manager = JiraOAuthManager(
        client_id=settings.JIRA_OAUTH_CLIENT_ID,
        client_secret=settings.JIRA_OAUTH_CLIENT_SECRET.get_secret_value()
    )
    access_token, cloud_id = await oauth_manager.ensure_valid_token(integration_id, workspace_id)
    jira_client = JiraAPIClient(access_token, cloud_id)
    
    # Fetch epic from Jira
    try:
        epic_issue = await jira_client.get_issue(
            epic_key,
            fields=["summary", "description", "project"]
        )
    except Exception as e:
        logger.error(f"Failed to fetch epic {epic_key} from Jira: {e}")
        return {
            "success": False,
            "error": f"Failed to fetch epic from Jira: {str(e)}"
        }
    
    # Extract epic description
    fields = epic_issue.get("fields", {})
    epic_title = fields.get("summary", "")
    epic_description_adf = fields.get("description", {})
    
    # Convert ADF to plain text
    epic_description = _extract_text_from_adf(epic_description_adf)
    full_epic_text = f"{epic_title}\n\n{epic_description}"
    
    logger.info(f"Fetched epic {epic_key} from Jira: {epic_title}")
    
    # Decompose the epic
    result = await decompose_epic(
        epic_description=full_epic_text,
        max_stories=max_stories,
        user_prompt=user_prompt
    )
    
    if not result.get("success"):
        return result
    
    # Push to Jira if requested
    if push_to_jira:
        stories = result.get("data", {}).get("stories", [])
        project_key = epic_issue["key"].split("-")[0]
        
        jira_results = []
        failed_stories = []
        
        for story in stories:
            try:
                # Create issue in Jira
                issue_data = {
                    "fields": {
                        "project": {"key": project_key},
                        "summary": story["title"],
                        "description": jira_client.convert_text_to_adf(
                            f"Persona: {story.get('persona', 'N/A')}\n\n"
                            f"Value: {story.get('user_value', 'N/A')}\n\n"
                            f"Acceptance Criteria:\n" + "\n".join([f"- {ac}" for ac in story.get("acceptance_criteria", [])])
                        ),
                        "issuetype": {"name": "Story"},
                        "customfield_10016": epic_key  # Epic link
                    }
                }
                
                created_issue = await jira_client.create_issue(issue_data)
                jira_results.append({
                    "title": story["title"],
                    "jira_key": created_issue["key"],
                    "jira_url": f"{jira_client.base_url}/browse/{created_issue['key']}"
                })
                logger.info(f"Created story in Jira: {created_issue['key']}")
                
            except Exception as e:
                logger.error(f"Failed to create story in Jira: {e}")
                failed_stories.append({
                    "title": story["title"],
                    "error": str(e)
                })
        
        result["jira_push_results"] = {
            "success": len(failed_stories) == 0,
            "created_count": len(jira_results),
            "failed_count": len(failed_stories),
            "created_stories": jira_results,
            "failed_stories": failed_stories
        }
    
    return result


def _extract_text_from_adf(adf: Dict) -> str:
    """
    Extract plain text from Atlassian Document Format.
    
    Args:
        adf: ADF document structure
        
    Returns:
        Plain text string
    """
    if not adf or not isinstance(adf, dict):
        return ""
    
    text_parts = []
    
    def extract_content(node):
        if isinstance(node, dict):
            node_type = node.get("type")
            
            if node_type == "text":
                text_parts.append(node.get("text", ""))
            elif node_type in ["paragraph", "heading", "listItem"]:
                if node.get("content"):
                    for child in node["content"]:
                        extract_content(child)
                    text_parts.append("\n")
            elif node.get("content"):
                for child in node["content"]:
                    extract_content(child)
        elif isinstance(node, list):
            for item in node:
                extract_content(item)
    
    if adf.get("content"):
        for content_node in adf["content"]:
            extract_content(content_node)
    
    return " ".join(text_parts).strip()


# ═══════════════════════════════════════════════════════════════════════════════
# DEMO / CLI
# ═══════════════════════════════════════════════════════════════════════════════

async def _demo():
    epic = (
        "As a product team we need an in-app notification center so users can see "
        "real-time updates about project events (new comments, status changes, assignments) "
        "without refreshing the page."
    )
    print("=" * 60)
    print("Epic Decomposition using OpenAI Agents SDK")
    print("=" * 60)
    print(f"Epic: {epic[:100]}...")
    print()
    
    result = await decompose_epic(epic, max_stories=5)
    
    print(f"Success: {result.get('success')}")
    print(f"Provider: {result.get('provider', 'unknown')}")
    
    data = result.get('data') or {}
    stories = data.get('stories') or []
    print(f"Stories generated: {len(stories)}")
    
    for i, story in enumerate(stories, 1):
        print(f"\n{i}. {story.get('title', 'No title')}")
        print(f"   Persona: {story.get('persona', 'N/A')}")
        print(f"   Value: {story.get('user_value', 'N/A')[:60]}...")
        ac = story.get('acceptance_criteria', [])
        print(f"   AC count: {len(ac)}")
    
    print(f"\nQuality score: {result.get('quality_score')}")
    print(f"Warnings: {result.get('warnings', [])}")


def run_demo_sync():
    """CLI entry point."""
    asyncio.run(_demo())


if __name__ == "__main__":
    run_demo_sync()
